### ISSUE TITLE
[REQUEST] ability to customize the thresholds and the colors

### ISSUE THREAD

**Issue by tigers75** [queimadus/cover-icon-element#7]
I like the add-in very much, it's the sort of thing that is surprinsigly missing in HA for such a common component.
But I'd like to have some more customization, for instance the ability to customize the color of the icons (it just messes with the picture in the background sometimes) or the ability to set the limits where one or the other icon is shown.
To clarify: I rarely close to 0% my blinds, it usually goes to 10/15% so I'd be nice for them to show as "closed" icon when under 15%.
I also have automations that set the % to 50% or 75% exactly, and 50% is still represented as a 25% open and not half open as it should be:
![image](https://user-images.githubusercontent.com/37505492/141344179-962e9c67-7cfc-4781-a950-1992c9c43ca1.png)
I believe that this could be considered a bug: at 50% open I expect the icon to show 50% open regardless of my personal taste.
The same goes for 75%, that is shown as "half open":
![image](https://user-images.githubusercontent.com/37505492/141344408-79acaf14-047a-4313-aaa3-134e38cdbd18.png)

**Comment by queimadus** [comment]
Hey @tigers75, glad the widget fits your needs as well.

The current percentages are:
```
    0 => 4 bars (fully closed)
 1-50 => 3 bars
51-77 => 2 bars
78-99 => 1 bars
  100 => 0 bars (fully open)
```

I believe the default for `4 bars` and `0 bars` should be reserved for the `0` and `100` positions respectively. This visually indicates the cover is either fully closed or fully open. 

The intermediate mappings of the cover's position to bars aren't divided linearly because when converting dumb covers to smart covers, setting the cover to 50% doesn't actually physically close the cover to 50% but in reality, it looks more like 75% closed. I suppose native smart covers don't suffer from this issue. I'll consider moving the default to something fairer like: 
```
    0 => 4 bars (fully closed)
 1-33 => 3 bars (32% interval)
34-66 => 2 bars (32% interval)
67-99 => 1 bars (32% interval)
  100 => 0 bars (fully open)
```

Either way, I think making it customizable makes sense! I'll expose a `positions` config that expects an array with 4 elements that set the bars breakpoints. E.g. `[1, 51, 78, 100]` will give us the current behaviour; `[1, 34, 67, 100]` the fair default behavior, and finally `[15, 50, 75, 100]` would match your described use case.

As for the color issue, I'd like to expose a config for the base color as well in the future.

**Comment by tigers75** [comment]
Hi,
while I agree that the extreme positions should be reserved for the 0 and 100 levels we must admit that this is a "personal" thing both in how that particular blind/shutter acts, as you say and in how we personally like to consider it as "open" or closed.

I personally use Tasmota for my covers, which features a way to correct for the shift in positioning you mention, so it can be set so that 50% is really half way up, while others may not... Also when they are opened or closed manually often people don't bother to get it to full 100 or 0 so the customization makes much sense if doable. In the meantime I'll fix it in the code termporarily.
I also tried to change the color (editing the 'fill' attribute in the svg data) but it doesn't work, think I'm missing something...

Thanks again for the great add in.

**Comment by queimadus** [comment]
This is now configurable via the `breakpoints` option (#8) in [v1.1.0](https://github.com/queimadus/cover-icon-element/releases/tag/v1.1.0) 🎉 

I'll close this issue and open a different one to track the ability to choose the icon's color.

**Comment by queimadus** [comment]
The color is now configurable via the `color` option (#10) in [v1.2.0](https://github.com/queimadus/cover-icon-element/releases/tag/v1.2.0) 🎉
